BOARD_TAG = ethernet
ARDUINO_PORT = /dev/ttyUSB0
#ARDMK_DIR = /home/zuhraa470/monitor-control-bunker/arduino-mk
ARDUINO_SKETCHBOOK = /home/zuhraa470/monitor-control/arduino-mk
ARDUINO_LIB_PATH = /home/zuhraa470/monitor-control/arduino-mk/libraries
ARDUINO_DIR = /home/zuhraa470/arduino-1.8.4
AVR_TOOLS_DIR=/usr
ARDUINO_LIBS = Wire SPI EEPROM Adafruit_HTU21DF_Library Adafruit_MCP9808_Library SparkFun_SX1509_Arduino_Library Ethernet Adafruit_SleepyDog
include ../Arduino.mk
